### ISSUE TITLE
Predicted SFT names fail if more SFTs than required are parsed

### ISSUE THREAD

**Issue by Rodrigo-Tenorio** [PyFstat/PyFstat#327]
`pyfstat.Writer` includes a sanity check which compares the output SFT's name produced by MFD to what one should expect according to the way in which this name is built.

`Makefakedata_v5` constructs the name once the SFTs are completely created: If one gives "too many SFTs" (expecting MFD to take care of selecting the required ones), that's fine, since the filename will be composed after selecting the appropriate files.

On the other hand, PyFstat creates the "predicted" filename *before* querying the appropriate frequency band. As a result, the number of SFTs included in the name is equal to the number of SFTs fed into MFD (regardless of its frequency band).

**Comment by dbkeitel** [comment]
For clarity, if I understand correctly: this occurs for frequency-segmented (split) SFT files. In a single file, the frequency band would have nothing to do with the number of SFTs. But in the split case, because we didn't think about that when coding up the sanity check, there's basically a spurious factor `Nfiles`.

**Comment by Rodrigo-Tenorio** [comment]
>  In a single file, the frequency band would have nothing to do with the number of SFTs. But in the split case, because we didn't think about that when coding up the sanity check, there's basically a spurious factor Nfiles.

That's exactly it.
