### ISSUE TITLE
improve binary support, add test cases / examples

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#37]
@Rodrigo-Tenorio continuing from #29:

> Also, I see that binary parameters are not supported for injection using this code... Since injections using noise SFT seem not to be supported (am I right?), there is need to focus on this issue by now.

Can you please open separate issues/PRs for any parts of the code where explicit binary support needs to be added, after this one is merged?

_Originally posted by @dbkeitel in https://github.com/PyFstat/PyFstat/pull/29#issuecomment-610361725_

Just to keep better track, I'm opening this one for now, and you can add more details if necessary. It would also be great to have some test cases and/or examples for binaries. Maybe a simple (and tiny!) grid search as a test case, and a simple one-stage follow-up example?

**Comment by Rodrigo-Tenorio** [comment]
Hi @dbkeitel , seems I made a mistake in comment, it should read "there is **no**need to focus on this issue by now". My bad.

What I meant is that PyFstat does not support the addition of noise via SFTs to the injections.
Hence, the only reason we would use this functionality would be to test a toy follow up for binary signals.

However, since PyFstat uses makefakedata, I guess it would not be that difficult to add this functionality and allow follow ups to be done using this tool only?

I'll start with this and think about it as I go.

**Comment by dbkeitel** [comment]
The injections / SFT generation part is actually one that should ideally be redone, since it currently calls MFD executables, while it would be cleaner to call the underlying functions directly through SWIG. However, none of us have time for it, and as you say, it should also be easy to add support for missing features through the current interface.

**Comment by Rodrigo-Tenorio** [comment]
Hi, started to work on this in abbd9f60a6f16b1ef36c5c6fd54c89af1b232b5d.
As you say, `make_sft.py` is screaming for a total rework (too many hard coded arguments in too many ways).

Bright side is injection parameters as given to mfd are read from a file rather than  formatted from object attributes, so that was the only part I had to accommodate for.

**Comment by dbkeitel** [comment]
Just for the record, keeping this open until #39 is merged.
