### ISSUE TITLE
Type annotations seem to be a bit incompatible with the return field

### ISSUE THREAD

**Issue by Rodrigo-Tenorio** [PyFstat/PyFstat#490]
See sphinx docs for `logging` and `injection_parameters`.

**Comment by dbkeitel** [comment]
@Rodrigo-Tenorio do you already have any idea of how to fix this up for next release? Not crucial though, just "nice to have".

**Comment by Rodrigo-Tenorio** [comment]
Probably https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_typehints ?

**Comment by dbkeitel** [comment]
Looks like this is a bug / not-yet-fully-implemented feature in sphinx, see: https://github.com/sphinx-doc/sphinx/issues/10134

The bad news is "added this to the some future version milestone", so no fix expected particularly soon.

I'd say for the moment the best solution is to duplicate the return type info with both `->` hints and `out: type` style. Since we only have a handful of hinted functions so far, @Rodrigo-Tenorio can you amend those?
