### ISSUE TITLE
release to pypi

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#73]
Would be really good to get this done for the next one. Just have to decide on a good tutorial to follow...

**Comment by GregoryAshton** [comment]
@dbkeitel this is relatively easy. Here are the rough steps:

1) Create a pypi account, I'd suggest creating a "pyfstat" account so that it can be easily transitioned between maintainers as needed.
2) Install twine: `pip install twine`
2) Run `$ python setup.py sdist`, this will create files in `dist/`
3) Run `$ twine upload dist/PACKAGENAME-VERSION.tar.gz` at this point it asks for your username and password.

The process can be automated into the CI (see, e.g. [here](https://git.ligo.org/lscsoft/bilby/-/blob/master/.gitlab-ci.yml#L147) in the bilby CI). 

A few details:
* The uploads need the setup.py to be formatted in a specific way and include some specific info. It looks all okay to me, but until you upload it is never certain.
* There is a test Pypi site (see [here](https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives))
* The uploads are permanent and irreversible. I.e. if you upload version 0.1.0, you can't re-upload with changes, you have to create 0.1.1 etc

Final note: currently my name is down on the "author". Since you are now much better places to manage this, I'd be happy if you want to change that to your email address.

**Comment by dbkeitel** [comment]
Thanks for the instructions!

Regarding the account, according to https://pypi.org/help/#collaborator-roles it should also be feasible that I just make a personal account, create a project with it and add you (or future co-maintainers) to the project.

**Comment by dbkeitel** [comment]
> Final note: currently my name is down on the "author". Since you are now much better places to manage this, I'd be happy if you want to change that to your email address.

According to https://www.python.org/dev/peps/pep-0345/ there are optional fields for a maintainer and their e-mail, while the `author_email` is also optional. So I'll:
- keep everyone as authors
- remove `author_email`
- list myself as main maintainer

Will first merge #66 to include Rodrigo, then get started on this.

**Comment by dbkeitel** [comment]
> warning: check: missing meta-data: if 'author' supplied, 'author_email' must be supplied too

-> will keep Greg's as the main `author_email` and mine as the `maintainer_email`.

**Comment by dbkeitel** [comment]
https://test.pypi.org/project/PyFstat/1.4/

Good enough for tonight, will double-check everything tomorrow.

Note this is not what will become the actual v1.4; it's just that the versioneer numbers like `1.3+200.2efe6483.clean` aren't legal for pypi (stuff with a "+" is a "local version") and so I needed to add a fake tag to the branch I was working on.

**Comment by dbkeitel** [comment]
@GregoryAshton do you think it makes sense to include the examples in the release distribution?

**Comment by GregoryAshton** [comment]
Yer I think packaging examples is a good idea.

**Comment by dbkeitel** [comment]
Done in #80 and with v1.4.0 : https://pypi.org/project/PyFstat/1.4.0/
